// Generated by CoffeeScript 1.4.0
(function() {
  var controls, m;

  controls = window.BC.namespace("controls");

  m = window.BC.namespace("model");

  $.extend(this, controls, m);

  describe("Models test", function() {
    it("", function() {});
    it("Shows a standart form", function() {
      return $('.suite').append(element(div({
        "class": "bs-docs-example"
      }, button("Default"), button.primary("Primary"), button.info("Info"), button.warning("Warning"), button.success("Success"), button.danger("Danger"), button.inverse("Inverse"), button.link())));
    });
    return it("Shows a dropdown button", function() {
      return $('.suite').append(element(div({
        "class": "bs-docs-example"
      }, dropdown(button.info("Hello"), a("Hi"), a("How"), divider(), a("Is it going?")), dropdown.segmented(button.info("Hello"), a("Hi"), a("How"), divider(), a("Is it going?")))));
    });
  });

}).call(this);
