// Generated by CoffeeScript 1.4.0
(function() {
  var controls, m;

  controls = window.BC.namespace("controls");

  m = window.BC.namespace("model");

  $.extend(this, controls, m);

  $('body').append(element(button('test', function() {
    return console.log('test');
  })));

  describe("Models test", function() {
    it("", function() {});
    it("Tests attr, css and text bindings", function() {
      var number, selectColor;
      number = model(0);
      selectColor = function(value) {
        if (value > 6) {
          return 'red';
        } else if (value > 3) {
          return 'orange';
        } else {
          return 'green';
        }
      };
      return $('.suite').append(element(div(button("Test", function() {
        return number(number() + 1);
      }).bindDisabled(number, function() {
        return number() === 10;
      }), span().bindText(number).bindCss(number, function() {
        return {
          color: selectColor(number())
        };
      }))));
    });
    return it("Tests visible and html bindings", function() {
      var isThree, number;
      number = model(0);
      isThree = function() {
        return number() === 3;
      };
      return $('.suite').append(element(div(p("You've clicked ", span("").bindText(number), " times"), button("Click me", function() {
        return number(number() + 1);
      }).bindDisabled(number, isThree), p("That's too many clicks! Please stop before you wear out your fingers. ", button('Reset Clicks', function() {
        return number(0);
      })).bindVisible(number, isThree))));
    });
  });

}).call(this);
