// Generated by CoffeeScript 1.4.0
(function() {
  var controls, i, m, number;

  controls = window.BC.namespace("controls");

  m = window.BC.namespace("model");

  $.extend(this, controls, m);

  i = 0;

  number = model(i);

  element(div("", button("Test", function() {
    return number(++i);
  }), span("0").bind(number)));

  describe("Models test", function() {
    it("Mente", function() {});
    i = 0;
    number = model(i);
    return it("Tests integer model", function() {
      return $('.suite').append(element(div("", button("Test", function() {
        return number(++i);
      }), span().bind(number))));
    });
  });

}).call(this);
