// Generated by CoffeeScript 1.4.0
(function() {
  var clickable, common, composite, html, single;

  html = window.BC.namespace("html");

  common = window.BC.namespace("common");

  $.extend(this, common);

  composite = ['abbr', 'address', 'b', 'blockquote', 'caption', 'cite', 'code', 'dd', 'div', 'dl', 'dt', 'em', 'fieldset', 'footer', 'form', 'h1', 'h2', 'h3', 'h5', 'h6', 'header', 'label', 'legend', 'li', 'nav', 'ol', 'optgroup', 'option', 'p', 'pre', 'q', 'section', 'small', 'span', 'strong', 'sub', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'tt', 'u', 'ul'];

  clickable = ['a', 'button'];

  single = ['br', 'hr'];

  html.div = tag("div");

  html.input = function(config) {
    return tag('input', config)().observable().on('keyup change', function(e) {
      return e.data.publish($(this).val());
    });
  };

  html.input.text = function() {
    return html.input({
      type: 'text'
    });
  };

  html.span = tag("span");

  html.button = function(name, click) {
    return tag('button')(name).on('click', click);
  };

}).call(this);
