// Generated by CoffeeScript 1.4.0
(function() {
  var common, models, util;

  common = window.BC.namespace("common");

  models = window.BC.namespace("models");

  util = window.BC.namespace("test.util");

  $.extend(this, common, models, util);

  describe("Model tests", function() {
    return it("Tests model", function() {
      var expectedValue, flag, subscriptionCalls;
      flag = model(true);
      expect(flag()).toBe(true);
      subscriptionCalls = 0;
      expectedValue = false;
      flag.subscribe(function(value) {
        subscriptionCalls++;
        return expect(value).toBe(expectedValue);
      });
      flag(false);
      expect(subscriptionCalls).toBe(1);
      expectedValue = 1;
      flag(1);
      expect(subscriptionCalls).toBe(2);
      expectedValue = "test";
      flag("test");
      return expect(subscriptionCalls).toBe(3);
    });
  });

}).call(this);
