// Generated by CoffeeScript 1.4.0
(function() {
  var bootstrap, common, models, util;

  common = window.BC.namespace("common");

  models = window.BC.namespace("models");

  util = window.BC.namespace("test.util");

  bootstrap = window.BC.namespace("bootstrap");

  $.extend(this, common, models, util, bootstrap);

  describe("Bindings test", function() {
    it("Empty test", function() {});
    return it("Tests dropdown button", function() {
      var value;
      value = "";
      return show(dropdown(button("Test", function() {
        return value = "Button";
      }), a("Item1", function() {
        return value = "1";
      }), a("Item2", function() {
        return value = "2";
      })));
    });
  });

}).call(this);
