// Generated by CoffeeScript 1.4.0
(function() {
  var ENTER_KEY, active, all, allDone, app, checkAll, completed, filter, html, info, main, models, pluralize, renderTodo, selectedFilter, textInput, todoModel, todos, todosFooter, todosHeader;

  html = window.BC.namespace("html");

  models = window.BC.namespace("models");

  $.extend(this, html, models);

  ENTER_KEY = 13;

  todoModel = function(title) {
    return object({
      title: title,
      completed: false
    });
  };

  todos = collection();

  checkAll = model(false);

  selectedFilter = model("");

  pluralize = function(count) {
    if (count === 1) {
      return "1 item";
    } else {
      return count + " items";
    }
  };

  all = function() {
    return true;
  };

  completed = function(todo) {
    return todo.completed;
  };

  active = function(todo) {
    return !todo.completed;
  };

  allDone = function() {
    var todo;
    return _.all((function() {
      var _i, _len, _ref, _results;
      _ref = todos();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todo = _ref[_i];
        _results.push(todo.completed);
      }
      return _results;
    })());
  };

  textInput = function(config, model, handler) {
    config['autofocus'] = true;
    return input.text(config, model).on('keydown', function(e) {
      if (e.keyCode === ENTER_KEY) {
        return handler();
      }
    }).on('blur', function() {
      return handler();
    });
  };

  filter = function(hash, name) {
    return a({
      href: hash
    }, name, function() {
      return location.hash = hash;
    }).bindClass(selectedFilter, function() {
      if (selectedFilter() === name) {
        return 'selected';
      }
    });
  };

  todosHeader = function() {
    var todoText;
    todoText = model("");
    return header({
      id: "header"
    }, h1("todos"), textInput({
      id: "new-todo",
      placeholder: "What needs to be done?"
    }, todoText, function() {
      if (todoText().trim()) {
        return todos.add(todoModel(todoText("")));
      }
    }));
  };

  main = function() {
    return section({
      id: "main"
    }, input.checkbox({
      id: "toggle-all"
    }, checkAll).on('click', function() {
      var todo, _i, _len, _ref, _results;
      _ref = todos();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todo = _ref[_i];
        _results.push(todo.completed = checkAll());
      }
      return _results;
    }), label({
      "for": "toggle-all"
    }, "Mark all as complete"), ul({
      id: "todo-list"
    }).foreach(todos, renderTodo)).bindVisible(todos, function() {
      return todos.count() > 0;
    });
  };

  renderTodo = function(todo) {
    var content, edit, editing, view;
    edit = function() {
      return textInput({
        "class": "edit",
        autofocus: true
      }, bind(todo.title), function() {
        return content(view());
      });
    };
    view = function() {
      return div({
        "class": "view"
      }, input.checkbox({
        "class": "toggle"
      }, bind(todo.completed)).on('click', function() {
        checkAll(allDone());
        return true;
      }), label(bind(todo.title)).on('dblclick', function() {
        return content(edit());
      }), button({
        "class": "destroy"
      }, function() {
        return todos.remove(todo);
      }));
    };
    content = model(view());
    editing = false;
    content.subscribe(function() {
      return editing = !editing;
    });
    return li(content).bindClass(bind(todo.completed), function() {
      if (todo.completed) {
        return 'completed';
      }
    }).bindClass(content, function() {
      if (editing) {
        return 'editing';
      }
    });
  };

  todosFooter = function() {
    return footer({
      id: "footer"
    }, span({
      id: "todo-count"
    }, map(todos, function() {
      return pluralize(todos.count(active)) + " left";
    })), ul({
      id: "filters"
    }, li(filter('#/', "All")).addClass('selected'), li(filter('#/active', "Active")), li(filter('#/completed', "Completed"))), button({
      id: "clear-completed"
    }, map(todos, function() {
      return "Clear completed (" + todos.total(completed) + ")";
    }), function() {
      return todos.remove(completed);
    }).bindVisible(todos, function() {
      return todos.total(completed) > 0;
    })).bindVisible(todos, function() {
      return todos.total() > 0;
    });
  };

  info = function() {
    return footer({
      id: "info"
    }, p("Double-click to edit a todo"), p('Created by <a href="http://todomvc.com">you</a>'), p('Part of <a href="http://todomvc.com">TodoMVC</a>'));
  };

  body(section({
    id: "todoapp"
  }, todosHeader(), main(), todosFooter(), info()));

  app = Sammy('#main', function() {
    this.get('#/', function() {
      selectedFilter('All');
      return todos.filter(all);
    });
    this.get('#/active', function() {
      selectedFilter('Active');
      return todos.filter(active);
    });
    return this.get('#/completed', function() {
      selectedFilter('Completed');
      return todos.filter(completed);
    });
  });

  $(function() {
    return app.run('#/');
  });

}).call(this);
