// Generated by CoffeeScript 1.4.0
(function() {
  var bootstrap, common, models, util;

  common = window.BC.namespace("common");

  models = window.BC.namespace("models");

  util = window.BC.namespace("test.util");

  bootstrap = window.BC.namespace("bootstrap");

  $.extend(this, common, models, util, bootstrap);

  describe("Bindings test", function() {
    return it("Tests observable", function() {
      var calls, listener, o;
      o = observable();
      calls = 0;
      listener = function() {
        return calls++;
      };
      o.subscribe(listener);
      o.subscribe(listener);
      o.subscribe(listener);
      o.publish(1);
      expect(calls).toBe(1);
      o.publish(2);
      return expect(calls).toBe(2);
    });
  });

}).call(this);
