// Generated by CoffeeScript 1.4.0
(function() {
  var common, models;

  models = window.BC.namespace("models");

  common = window.BC.namespace("common");

  models.model = function(arg) {
    var model, o, value;
    value = arg;
    o = common.observable();
    model = function(newValue) {
      if (_.isUndefined(newValue)) {
        return value;
      } else {
        value = newValue;
        o.publish(value);
        return value;
      }
    };
    model.subscribe = function(listener) {
      return o.subscribe(listener);
    };
    return model;
  };

}).call(this);
