// Generated by CoffeeScript 1.4.0
(function() {
  var common, models,
    __slice = [].slice;

  models = window.BC.namespace("models");

  common = window.BC.namespace("common");

  models.model = function(arg) {
    var element, key, obj, value, _i, _len, _results;
    if (_.isString(arg)) {
      return ko.observable(arg);
    } else if (_.isNumber(arg)) {
      return ko.observable(arg);
    } else if (_.isBoolean(arg)) {
      return ko.observable(arg);
    } else if (_.isFunction(arg)) {
      return ko.observable(arg);
    } else if (_.isArray(arg)) {
      return ko.observableArray((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arg.length; _i < _len; _i++) {
          element = arg[_i];
          _results.push(model(element));
        }
        return _results;
      })());
    } else if (_.isUndefined()) {
      return arg;
    } else if (_.isObject(arg)) {
      obj = {};
      _results = [];
      for (value = _i = 0, _len = object.length; _i < _len; value = ++_i) {
        key = object[value];
        _results.push(obj[key] = model(value));
      }
      return _results;
    }
  };

  models.collection = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return ko.observableArray(args);
  };

}).call(this);
