// Generated by CoffeeScript 1.4.0
(function() {

  window.BC.define('store', function(store) {
    store.localStore = function() {
      return {
        post: (function() {}),
        put: (function() {}),
        get: (function() {}),
        getAll: (function() {}),
        "delete": (function() {})
      };
    };
    store.mongoLab = function() {
      var apiKey;
      apiKey = "xR9PQZeYGV7K40N8rXp_RpdJMjQXAgiD";
      return {
        post: function(obj) {},
        put: function(obj) {},
        get: function(obj) {},
        getAll: function(obj) {},
        "delete": function(obj) {}
      };
    };
    store.notifications = function() {
      return {
        post: function() {},
        put: function() {},
        get: function() {},
        getAll: function() {},
        "delete": function() {}
      };
    };
    return store.pusherNotifications = function() {
      return {
        post: function() {},
        put: function() {},
        get: function() {},
        getAll: function() {},
        "delete": function() {}
      };
    };
  });

}).call(this);
