// Generated by CoffeeScript 1.4.0
(function() {
  var buttonElement, common, controls, mixins;

  controls = window.BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  common = window.BC.namespace("common");

  $.extend(this, common);

  buttonElement = function(classes, name, click) {
    return tag('button')(classes, name).on('click', click);
  };

  controls.button = curry(buttonElement, 'btn');

}).call(this);
