// Generated by CoffeeScript 1.4.0
(function() {
  var common, nextId,
    __slice = [].slice;

  common = window.BC.namespace("common");

  common.toHtml = function(item) {
    var subitem;
    if (_.isFunction(item.html)) {
      return item.html();
    } else if (_.isString(item)) {
      return item;
    } else if (_.isNumber(item)) {
      return item;
    } else if (_.isUndefined(item)) {
      return "";
    } else if (_.isArray(item)) {
      return ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = item.length; _i < _len; _i++) {
          subitem = item[_i];
          _results.push(common.toHtml(subitem));
        }
        return _results;
      })()).join(" ");
    } else {
      throw Error(item + " is expected to be String, Number, Array, undefined or have .html() function");
    }
  };

  common.init = function(item, context) {
    var subitem;
    if (_.isFunction(item.init)) {
      return item.init(context);
    } else if (_.isString(item)) {

    } else if (_.isNumber(item)) {

    } else if (_.isUndefined(item)) {

    } else if (_.isArray(item)) {
      return ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = item.length; _i < _len; _i++) {
          subitem = item[_i];
          _results.push(common.init(subitem, context));
        }
        return _results;
      })()).join(" ");
    } else {
      throw Error(item + " is expected to be String, Number, Array, undefined or have .init() function");
    }
  };

  nextId = (function() {
    var id;
    id = 0;
    return function() {
      return ++id;
    };
  })();

  common.tag = function(name, classes) {
    if (classes == null) {
      classes = "";
    }
    return function() {
      var addClass, addInitializer, binder, el, id, initializers, items;
      items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      id = 0;
      el = null;
      initializers = [];
      addInitializer = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (!id) {
          id = nextId();
        }
        initializers.push(args);
        return this;
      };
      binder = function(f) {
        return function(observable, map) {
          if (map == null) {
            map = function(x) {
              return x;
            };
          }
          addInitializer(f, map(observable()));
          observable.subscribe(function(newValue) {
            return el[f](map(newValue));
          });
          return this;
        };
      };
      addClass = function(name) {
        if (name) {
          if (classes) {
            return classes += " " + name;
          } else {
            return classes = name;
          }
        }
      };
      if (items.length > 0 && _.isObject(items[0]) && _.keys(items[0]).length === 1 && items[0]["class"]) {
        addClass(items[0]["class"]);
        items = _.rest(items);
      }
      return {
        id: function(value) {
          if (value) {
            id = value;
          } else {
            if (!id) {
              id = nextId();
            }
          }
          return this;
        },
        html: function() {
          return _.template("<" + name + " <% if (classes) { %><%='class=\"' + classes + '\"' %> <% } %> <% if (id) { %><%='id=\"' + id + '\"'%><% } %>><% _.each(items, function(item) { %>\n  <%=toHtml(item)%>\n<% }) %></" + name + ">", {
            items: items,
            toHtml: common.toHtml,
            classes: classes,
            id: id
          });
        },
        init: function(context) {
          var initializer, method, params, _i, _len, _results;
          common.init(items, context);
          if (id) {
            el = context.find('#' + id).first();
          }
          _results = [];
          for (_i = 0, _len = initializers.length; _i < _len; _i++) {
            initializer = initializers[_i];
            method = initializer[0];
            params = _.rest(initializer);
            _results.push(el[method].apply(el, params));
          }
          return _results;
        },
        addClass: function(name) {
          addClass(name);
          return this;
        },
        addItems: function() {
          var newItems;
          newItems = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          items = items.concat(newItems);
          return this;
        },
        bindValue: binder('val'),
        bindText: binder('text'),
        bindHtml: binder('html'),
        bindCss: binder('css'),
        bindStyle: binder('style'),
        bindClass: binder('class'),
        bindVisible: function(observable, condition) {
          return this.bindCss(observable, function(value) {
            return {
              display: condition(value) ? "" : "none"
            };
          });
        },
        bindDisabled: function(observable, condition) {
          return this.bindProp(observable, function(value) {
            return {
              disabled: condition(value)
            };
          });
        },
        bindAttr: binder('attr'),
        bindProp: binder('prop'),
        on: function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          addInitializer.apply(null, ['on'].concat(__slice.call(args)));
          return this;
        },
        foreach: function(collection, render) {
          var item, _i, _len, _ref,
            _this = this;
          this.id();
          _ref = collection();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            items.push(render(item));
          }
          collection.subscribe(function(newItems) {
            var elements;
            elements = (function() {
              var _j, _len1, _results;
              _results = [];
              for (_j = 0, _len1 = newItems.length; _j < _len1; _j++) {
                item = newItems[_j];
                _results.push(common.element(render(item)));
              }
              return _results;
            })();
            return el.html(elements);
          });
          return this;
        },
        addClassAndItems: function() {
          var items, name;
          name = arguments[0], items = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          this.addClass(name);
          return this.addItems.apply(this, items);
        }
      };
    };
  };

  common.element = function(composite) {
    var el;
    el = $(composite.html());
    composite.init(el);
    return el;
  };

  common.partial = function() {
    var fixedArgs, fn;
    fn = arguments[0], fixedArgs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return fn.apply(null, fixedArgs.concat(args));
    };
  };

}).call(this);
