// Generated by CoffeeScript 1.4.0
(function() {
  var common, datePicker, dateTimePicker, nextId, timePicker;

  common = window.BC.namespace("common");

  nextId = (function() {
    var id;
    id = 0;
    return function() {
      return ++id;
    };
  })();

  timePicker = function(config) {
    var el;
    return el = input.text().timepicker(config);
  };

  datePicker = function(config) {
    return input.text().datepicker();
  };

  dateTimePicker = function() {
    var date, time;
    time = timePicker();
    return date = datePicker();
  };

}).call(this);
