// Generated by CoffeeScript 1.6.3
(function() {
  var initializers, modules;

  modules = {};

  initializers = {};

  window.BC = {
    namespace: function(name) {
      var initializer, _i, _len, _ref;
      if (_.isUndefined(modules[name])) {
        modules[name] = {};
      }
      if (_.isArray(initializers[name])) {
        _ref = initializers[name];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          initializer = _ref[_i];
          initializer(modules[name]);
        }
        initializers[name] = void 0;
      }
      return modules[name];
    },
    define: function(name, fn) {
      if (_.isUndefined(initializers[name])) {
        return initializers[name] = [fn];
      } else {
        return initializers[name].push(fn);
      }
    }
  };

}).call(this);
