// Generated by CoffeeScript 1.4.0
(function() {

  window.BC = {
    namespace: function(name) {
      var _base, _ref;
      return (_ref = (_base = window.BC)[name]) != null ? _ref : _base[name] = {};
    }
  };

}).call(this);
