// Generated by CoffeeScript 1.4.0
(function() {
  var common, controls, divElement, mixins,
    __slice = [].slice;

  controls = window.BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  common = window.BC.namespace("common");

  $.extend(this, common);

  divElement = tag("div");

  controls.div = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (args.length !== 0) {
      return divElement.apply(null, args);
    } else {
      return $.extend(mixins.control(), mixins.composite(divElement), mixins.spannable(), mixins.offsetable());
    }
  };

  controls.div.row = curry(divElement, "row");

  controls.div.row.fluid = curry(divElement, "row-fluid");

  controls.div.container = curry(divElement, "container");

  controls.div.container.fluid = curry(divElement, "container-fluid");

}).call(this);
