// Generated by CoffeeScript 1.4.0
(function() {
  var button, common, controls, mixins;

  controls = window.BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  common = window.BC.namespace("common");

  $.extend(this, common);

  button = function(classes) {
    return function(name, click) {
      return tag('button')(name).addClass(classes).on('click', click);
    };
  };

  controls.button = button('btn');

}).call(this);
