// Generated by CoffeeScript 1.4.0
(function() {
  var common, controls, icon;

  controls = window.BC.namespace("controls");

  common = window.BC.namespace("common");

  icon = function(icon) {
    return "<i class='" + icon + "'></i>";
  };

  controls.icon = tag('i');

  controls.icon.glass = icon('icon-glass');

  controls.icon.music = icon('icon-music');

  controls.icon.search = icon('icon-search');

  controls.icon.envelope = icon('icon-envelope');

  controls.icon.heart = icon('icon-heart');

  controls.icon.star = icon('icon-star');

  controls.icon.star_empty = icon('icon-star-empty');

  controls.icon.user = icon('icon-user');

  controls.icon.film = icon('icon-film');

  controls.icon.th_large = icon('icon-th-large');

  controls.icon.th = icon('icon-th');

  controls.icon.th_list = icon('icon-th-list');

  controls.icon.ok = icon('icon-ok');

  controls.icon.remove = icon('icon-remove');

  controls.icon.zoom_in = icon('icon-zoom-in');

  controls.icon.zoom_out = icon('icon-zoom-out');

  controls.icon.off = icon('icon-off');

  controls.icon.signal = icon('icon-signal');

  controls.icon.cog = icon('icon-cog');

  controls.icon.trash = icon('icon-trash');

  controls.icon.home = icon('icon-home');

  controls.icon.file = icon('icon-file');

  controls.icon.time = icon('icon-time');

  controls.icon.road = icon('icon-road');

  controls.icon.download_alt = icon('icon-download-alt');

  controls.icon.download = icon('icon-download');

  controls.icon.upload = icon('icon-upload');

  controls.icon.inbox = icon('icon-inbox');

  controls.icon.play_circle = icon('icon-play-circle');

  controls.icon.repeat = icon('icon-repeat');

  controls.icon.refresh = icon('icon-refresh');

  controls.icon.list_alt = icon('icon-list-alt');

  controls.icon.lock = icon('icon-lock');

  controls.icon.flag = icon('icon-flag');

  controls.icon.headphones = icon('icon-headphones');

  controls.icon.volume_off = icon('icon-volume-off');

  controls.icon.volume_down = icon('icon-volume-down');

  controls.icon.volume_up = icon('icon-volume-up');

  controls.icon.qrcode = icon('icon-qrcode');

  controls.icon.barcode = icon('icon-barcode');

  controls.icon.tag = icon('icon-tag');

  controls.icon.tags = icon('icon-tags');

  controls.icon.book = icon('icon-book');

  controls.icon.bookmark = icon('icon-bookmark');

  controls.icon.print = icon('icon-print');

  controls.icon.camera = icon('icon-camera');

  controls.icon.font = icon('icon-font');

  controls.icon.bold = icon('icon-bold');

  controls.icon.italic = icon('icon-italic');

  controls.icon.text_height = icon('icon-text-height');

  controls.icon.text_width = icon('icon-text-width');

  controls.icon.align_left = icon('icon-align-left');

  controls.icon.align_center = icon('icon-align-center');

  controls.icon.align_right = icon('icon-align-right');

  controls.icon.align_justify = icon('icon-align-justify');

  controls.icon.list = icon('icon-list');

  controls.icon.indent_left = icon('icon-indent-left');

  controls.icon.indent_right = icon('icon-indent-right');

  controls.icon.facetime_video = icon('icon-facetime-video');

  controls.icon.picture = icon('icon-picture');

  controls.icon.pencil = icon('icon-pencil');

  controls.icon.map_marker = icon('icon-map-marker');

  controls.icon.adjust = icon('icon-adjust');

  controls.icon.tint = icon('icon-tint');

  controls.icon.edit = icon('icon-edit');

  controls.icon.share = icon('icon-share');

  controls.icon.check = icon('icon-check');

  controls.icon.move = icon('icon-move');

  controls.icon.step_backward = icon('icon-step-backward');

  controls.icon.fast_backward = icon('icon-fast-backward');

  controls.icon.backward = icon('icon-backward');

  controls.icon.play = icon('icon-play');

  controls.icon.pause = icon('icon-pause');

  controls.icon.stop = icon('icon-stop');

  controls.icon.forward = icon('icon-forward');

  controls.icon.fast_forward = icon('icon-fast-forward');

  controls.icon.step_forward = icon('icon-step-forward');

  controls.icon.eject = icon('icon-eject');

  controls.icon.chevron_left = icon('icon-chevron-left');

  controls.icon.chevron_right = icon('icon-chevron-right');

  controls.icon.plus_sign = icon('icon-plus-sign');

  controls.icon.minus_sign = icon('icon-minus-sign');

  controls.icon.remove_sign = icon('icon-remove-sign');

  controls.icon.ok_sign = icon('icon-ok-sign');

  controls.icon.question_sign = icon('icon-question-sign');

  controls.icon.info_sign = icon('icon-info-sign');

  controls.icon.screenshot = icon('icon-screenshot');

  controls.icon.remove_circle = icon('icon-remove-circle');

  controls.icon.ok_circle = icon('icon-ok-circle');

  controls.icon.ban_circle = icon('icon-ban-circle');

  controls.icon.arrow_left = icon('icon-arrow-left');

  controls.icon.arrow_right = icon('icon-arrow-right');

  controls.icon.arrow_up = icon('icon-arrow-up');

  controls.icon.arrow_down = icon('icon-arrow-down');

  controls.icon.share_alt = icon('icon-share-alt');

  controls.icon.resize_full = icon('icon-resize-full');

  controls.icon.resize_small = icon('icon-resize-small');

  controls.icon.plus = icon('icon-plus');

  controls.icon.minus = icon('icon-minus');

  controls.icon.asterisk = icon('icon-asterisk');

  controls.icon.exclamation_sign = icon('icon-exclamation-sign');

  controls.icon.gift = icon('icon-gift');

  controls.icon.leaf = icon('icon-leaf');

  controls.icon.fire = icon('icon-fire');

  controls.icon.eye_open = icon('icon-eye-open');

  controls.icon.eye_close = icon('icon-eye-close');

  controls.icon.warning_sign = icon('icon-warning-sign');

  controls.icon.plane = icon('icon-plane');

  controls.icon.calendar = icon('icon-calendar');

  controls.icon.random = icon('icon-random');

  controls.icon.comment = icon('icon-comment');

  controls.icon.magnet = icon('icon-magnet');

  controls.icon.chevron_up = icon('icon-chevron-up');

  controls.icon.chevron_down = icon('icon-chevron-down');

  controls.icon.retweet = icon('icon-retweet');

  controls.icon.shopping_cart = icon('icon-shopping-cart');

  controls.icon.folder_close = icon('icon-folder-close');

  controls.icon.folder_open = icon('icon-folder-open');

  controls.icon.resize_vertical = icon('icon-resize-vertical');

  controls.icon.resize_horizontal = icon('icon-resize-horizontal');

  controls.icon.hdd = icon('icon-hdd');

  controls.icon.bullhorn = icon('icon-bullhorn');

  controls.icon.bell = icon('icon-bell');

  controls.icon.certificate = icon('icon-certificate');

  controls.icon.thumbs_up = icon('icon-thumbs-up');

  controls.icon.thumbs_down = icon('icon-thumbs-down');

  controls.icon.hand_right = icon('icon-hand-right');

  controls.icon.hand_left = icon('icon-hand-left');

  controls.icon.hand_up = icon('icon-hand-up');

  controls.icon.hand_down = icon('icon-hand-down');

  controls.icon.circle_arrow_right = icon('icon-circle-arrow-right');

  controls.icon.circle_arrow_left = icon('icon-circle-arrow-left');

  controls.icon.circle_arrow_up = icon('icon-circle-arrow-up');

  controls.icon.circle_arrow_down = icon('icon-circle-arrow-down');

  controls.icon.globe = icon('icon-globe');

  controls.icon.wrench = icon('icon-wrench');

  controls.icon.tasks = icon('icon-tasks');

  controls.icon.filter = icon('icon-filter');

  controls.icon.briefcase = icon('icon-briefcase');

  controls.icon.fullscreen = icon('icon-fullscreen');

}).call(this);
