// Generated by CoffeeScript 1.4.0
(function() {
  var common, controls, div, mixins,
    __slice = [].slice;

  controls = window.BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  common = window.BC.namespace("common");

  $.extend(this, common);

  div = function(className) {
    if (className == null) {
      className = "";
    }
    return function() {
      var items;
      items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return $.extend(tag('div').apply(null, items).addClass(className), mixins.spannable(), mixins.offsetable());
    };
  };

  controls.div = div();

  controls.div.row = div("row");

  controls.div.row.fluid = div("row-fluid");

  controls.div.container = div("container");

  controls.div.container.fluid = div("container-fluid");

}).call(this);
