// Generated by CoffeeScript 1.4.0
(function() {
  var common, controls, mixins,
    __slice = [].slice;

  common = BC.namespace("common");

  controls = BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  $.extend(this, common);

  controls.table = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag('table', 'table').apply(null, args), {
      stripped: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return this.addClassAndItems.apply(this, ['table-striped'].concat(__slice.call(items)));
      },
      bordered: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return this.addClassAndItems.apply(this, ['table-bordered'].concat(__slice.call(items)));
      },
      hover: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return this.addClassAndItems.apply(this, ['table-hover'].concat(__slice.call(items)));
      },
      condensed: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return this.addClassAndItems.apply(this, ['table-condensed'].concat(__slice.call(items)));
      }
    });
  };

  controls.tr = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag('tr').apply(null, args), mixins.contextual(''));
  };

  controls.td = tag('td');

  controls.thead = tag('thead');

  controls.tbody = tag('tbody');

  controls.th = tag('th');

  controls.caption = tag('caption');

}).call(this);
