// Generated by CoffeeScript 1.4.0
(function() {
  var common, controls, mixins,
    __slice = [].slice;

  common = BC.namespace("common");

  controls = BC.namespace("controls");

  mixins = window.BC.namespace("mixins");

  $.extend(this, common);

  controls.table = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag('table', 'table').apply(null, args), {
      stripped: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.addClass('table-striped');
        return this.addItems.apply(this, items);
      },
      bordered: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.addClass('table-bordered');
        return this.addItems.apply(this, items);
      },
      hover: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.addClass('table-hover');
        return this.addItems.apply(this, items);
      },
      condensed: function() {
        var items;
        items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.addClass('table-condensed');
        return this.addItems.apply(this, items);
      }
    });
  };

  controls.tr = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag('tr').apply(null, args), mixins.contextual(''));
  };

  controls.td = tag('td');

  controls.thead = tag('thead');

  controls.tbody = tag('tbody');

  controls.th = tag('th');

  controls.caption = tag('caption');

}).call(this);
