// Generated by CoffeeScript 1.4.0
(function() {
  var __slice = [].slice;

  window.BC.define('bootstrap', function(bootstrap) {
    var common, mixins;
    common = window.BC.namespace("common");
    mixins = window.BC.namespace("bootstrap.mixins");
    $.extend(this, common);
    bootstrap.table = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return $.extend(tag('table', {
        "class": 'table'
      }).apply(null, args), {
        stripped: function() {
          var items;
          items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.addClassAndItems.apply(this, ['table-striped'].concat(__slice.call(items)));
        },
        bordered: function() {
          var items;
          items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.addClassAndItems.apply(this, ['table-bordered'].concat(__slice.call(items)));
        },
        hover: function() {
          var items;
          items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.addClassAndItems.apply(this, ['table-hover'].concat(__slice.call(items)));
        },
        condensed: function() {
          var items;
          items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.addClassAndItems.apply(this, ['table-condensed'].concat(__slice.call(items)));
        }
      });
    };
    bootstrap.tr = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return $.extend(tag('tr').apply(null, args), mixins.contextual(''));
    };
    bootstrap.td = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return $.extend(tag('td').apply(null, args), mixins.spannable());
    };
    bootstrap.thead = tag('thead');
    bootstrap.tbody = tag('tbody');
    bootstrap.th = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return $.extend(tag('th').apply(null, args), mixins.spannable());
    };
    return bootstrap.caption = tag('caption');
  });

}).call(this);
