// Generated by CoffeeScript 1.4.0
(function() {
  var bootstrap, common, h, mixins,
    __slice = [].slice;

  common = BC.namespace("common");

  bootstrap = window.BC.namespace("bootstrap");

  mixins = window.BC.namespace("bootstrap.mixins");

  $.extend(this, common);

  h = function(size) {
    return tag("h" + size);
  };

  bootstrap.h1 = h(1);

  bootstrap.h2 = h(2);

  bootstrap.h3 = h(3);

  bootstrap.h4 = h(4);

  bootstrap.h5 = h(5);

  bootstrap.h6 = h(6);

  bootstrap.p = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag("p").apply(null, args), mixins.textContextual(), {
      lead: function() {
        return this.addClass('lead');
      }
    });
  };

  bootstrap.span = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return $.extend(tag("span").apply(null, args), mixins.textContextual());
  };

  bootstrap.address = function() {
    var elements, value, values, _i, _len;
    values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    elements = [];
    for (_i = 0, _len = values.length; _i < _len; _i++) {
      value = values[_i];
      elements.push(value);
      elements.push('<br>');
    }
    elements.pop();
    return tag('address')(elements);
  };

  bootstrap.blockquote = tag('blockquote');

  bootstrap.small = tag('small');

  bootstrap.bold = tag('strong');

  bootstrap.strong = bootstrap.bold;

  bootstrap.italic = tag('em');

  bootstrap.em = bootstrap.italic;

  bootstrap.ul = tag('ul');

  bootstrap.ul.unstyled = tag('ul', {
    "class": 'unstyled'
  });

  bootstrap.ul.inline = tag('ul', {
    "class": 'inline'
  });

  bootstrap.li = tag('li');

  bootstrap.ol = tag('ol');

  bootstrap.dl = tag('dl');

  bootstrap.dl.horizontal = tag('dl', {
    "class": 'dl-horizontal'
  });

  bootstrap.dt = tag('dt');

  bootstrap.dd = tag('dd');

  bootstrap.code = tag('code');

  bootstrap.pre = tag('pre');

  bootstrap.pre.scrollable = tag('pre', {
    "class": '.pre-scrollable'
  });

  bootstrap.section = tag('section');

  bootstrap.pageHeader = tag('div', {
    "class": 'page-header'
  });

}).call(this);
